// <auto-generated />
using System;
using FitRank_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitRank_API.Migrations
{
    [DbContext(typeof(FitRankDbContext))]
    [Migration("20251030235650_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitRank_API.Domain.Entities.Actividad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan?>("Duracion")
                        .HasColumnType("interval");

                    b.Property<long>("EjercicioAsignadoId")
                        .HasColumnType("bigint");

                    b.Property<long>("EntrenamientoId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double?>("Punto")
                        .HasColumnType("double precision");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<long>("SerieId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioAsignadoId");

                    b.HasIndex("EntrenamientoId");

                    b.HasIndex("SerieId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionGrupoMuscular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("FactorProgresion")
                        .HasColumnType("double precision");

                    b.Property<long>("GrupoMuscularId")
                        .HasColumnType("bigint");

                    b.Property<double>("MultiplicadorPeso")
                        .HasColumnType("double precision");

                    b.Property<double>("MultiplicadorRepeticiones")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("ConfiguracionesGrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.DiaDeLaSemana", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiasDeLaSemana");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Dificultad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dificultades");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionEstimada")
                        .HasColumnType("integer");

                    b.Property<long>("GrupoMuscularId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaquinaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioAsignado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroEjercicio")
                        .HasColumnType("integer");

                    b.Property<long>("SesionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionId");

                    b.ToTable("EjerciciosAsignados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Entrenamiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan?>("Duracion")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Foto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdministradorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .IsUnique();

                    b.ToTable("Gimnasios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("GruposMusculares");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Invitacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatosPrellenados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MpPaymentId")
                        .HasColumnType("text");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Jornada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DiaDeLaSemanaId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<long>("ProfesorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiaDeLaSemanaId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Jornadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.LogroSocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaOtorgado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LogroId")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("integer");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.ToTable("LogrosSocios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.MedidaCorporal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("BrazoDerechoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("BrazoIzquierdoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CaderaCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CinturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PechoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("MedidasCorporales");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Notificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioEmisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioReceptorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioEmisorId");

                    b.HasIndex("UsuarioReceptorId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Puntaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Puntajes");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<long?>("AdministradorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("SocioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Serie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Duracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EjercicioAsignadoId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroDeSerie")
                        .HasColumnType("integer");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioAsignadoId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Sesion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroDeSesion")
                        .HasColumnType("integer");

                    b.Property<long>("RutinaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dni")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsActivado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoDePerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Administradores", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Sueldo")
                        .HasColumnType("double precision");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("Puntaje")
                        .HasColumnType("double precision");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.EjercicioAsignado", "EjercicioAsignado")
                        .WithMany()
                        .HasForeignKey("EjercicioAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Entrenamiento", "Entrenamiento")
                        .WithMany("Actividades")
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Serie", "Serie")
                        .WithMany("Actividades")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioAsignado");

                    b.Navigation("Entrenamiento");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Asistencias")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Asistencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionGrupoMuscular", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Configuraciones")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Ejercicios")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId");

                    b.Navigation("GrupoMuscular");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioAsignado", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany("EjerciciosAsignados")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Sesion", "Sesion")
                        .WithMany("EjerciciosAsignados")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Entrenamiento", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Foto", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("FotosProgreso")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Administrador", "Administrador")
                        .WithOne("Gimnasio")
                        .HasForeignKey("FitRank_API.Domain.Entities.Gimnasio", "AdministradorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Invitacion", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Invitaciones")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gimnasio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Jornada", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.DiaDeLaSemana", "DiaDeLaSemana")
                        .WithMany()
                        .HasForeignKey("DiaDeLaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDeLaSemana");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.LogroSocio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Logro", "Logro")
                        .WithMany("LogrosOtorgados")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany()
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.MedidaCorporal", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("MedidasCorporales")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "UsuarioEmisor")
                        .WithMany("NotificacionesEnviadas")
                        .HasForeignKey("UsuarioEmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "UsuarioReceptor")
                        .WithMany("NotificacionesRecibidas")
                        .HasForeignKey("UsuarioReceptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioEmisor");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Puntaje", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Administrador", null)
                        .WithMany("RutinasAsignadas")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("FitRank_API.Domain.Entities.Profesor", null)
                        .WithMany("RutinasAsignadas")
                        .HasForeignKey("ProfesorId");

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("RutinasAsignadas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RutinasCreadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Serie", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.EjercicioAsignado", "EjercicioAsignado")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioAsignado");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Sesion", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Rutina", "Rutina")
                        .WithMany("Sesiones")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Socios")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Socio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.Navigation("EjerciciosAsignados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioAsignado", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Entrenamiento", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Invitaciones");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("Configuraciones");

                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Navigation("LogrosOtorgados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Serie", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Sesion", b =>
                {
                    b.Navigation("EjerciciosAsignados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("NotificacionesEnviadas");

                    b.Navigation("NotificacionesRecibidas");

                    b.Navigation("RutinasCreadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("Gimnasio");

                    b.Navigation("RutinasAsignadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("RutinasAsignadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.Navigation("Entrenamientos");

                    b.Navigation("FotosProgreso");

                    b.Navigation("MedidasCorporales");

                    b.Navigation("RutinasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
