// <auto-generated />
using System;
using FitRank_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitRank_API.Migrations
{
    [DbContext(typeof(FitRankDbContext))]
    [Migration("20251027174022_Foto_MedidaCorporal_Administrador")]
    partial class Foto_MedidaCorporal_Administrador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdministradorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("SocioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionGrupoMuscular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupoMuscularId")
                        .HasColumnType("bigint");

                    b.Property<double>("Multiplicadopeso")
                        .HasColumnType("double precision");

                    b.Property<double>("MultiplicadorRepeticiones")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("ConfiguracionesGrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.DiaDeLaSemana", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiasDeLaSemana");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Dificultad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dificultades");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupoMuscularId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioAsignado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("Orden")
                        .HasColumnType("integer");

                    b.Property<long>("RutinaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Sesion")
                        .HasColumnType("integer");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.HasIndex("SocioId");

                    b.ToTable("EjerciciosAsignados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioRealizado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioId")
                        .HasColumnType("bigint");

                    b.Property<long>("RutinaId")
                        .HasColumnType("bigint");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.HasIndex("SocioId");

                    b.ToTable("EjerciciosRealizados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Foto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdministradorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .IsUnique();

                    b.ToTable("Gimnasios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GruposMusculares");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Invitacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatosPrellenados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MpPaymentId")
                        .HasColumnType("text");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.LogroSocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaOtorgado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LogroId")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("integer");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.ToTable("LogrosSocios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.MedidaCorporal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("BrazoDerechoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("BrazoIzquierdoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CaderaCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CinturaCm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PechoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("MedidasCorporales");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Puntaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SocioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Puntajes");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DificultadId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Frecuencia")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DificultadId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroDeSesion")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<long>("RutinaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinasEjercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SerieAsignada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioAsignadoId")
                        .HasColumnType("bigint");

                    b.Property<int>("NroSerie")
                        .HasColumnType("integer");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Rir")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioAsignadoId");

                    b.ToTable("SeriesAsignadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SerieRealizada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EjercicioRealizadoId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroDeSerie")
                        .HasColumnType("integer");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Rir")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioRealizadoId");

                    b.ToTable("SeriesRealizadas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SesionRealizadaDeEjercicios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroDeSesion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SesionRealizadaDeEjercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dni")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsActivado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoDePerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Administradores", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Sueldo")
                        .HasColumnType("double precision");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.HasBaseType("FitRank_API.Domain.Entities.Usuario");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GimnasioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("Puntaje")
                        .HasColumnType("double precision");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Administrador", null)
                        .WithMany("asistencias")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Asistencias")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Profesor", null)
                        .WithMany("asistencias")
                        .HasForeignKey("ProfesorId");

                    b.HasOne("FitRank_API.Domain.Entities.Socio", null)
                        .WithMany("asistencias")
                        .HasForeignKey("SocioId");

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gimnasio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionGrupoMuscular", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany()
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany()
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioAsignado", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioRealizado", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Foto", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("FotosProgreso")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Administrador", "Administrador")
                        .WithOne("Gimnasio")
                        .HasForeignKey("FitRank_API.Domain.Entities.Gimnasio", "AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Invitacion", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Invitaciones")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gimnasio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.LogroSocio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Logro", "Logro")
                        .WithMany("LogrosOtorgados")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany()
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.MedidaCorporal", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("MedidasCorporales")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Puntaje", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Dificultad", "Dificultad")
                        .WithMany()
                        .HasForeignKey("DificultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dificultad");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SerieAsignada", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.EjercicioAsignado", "EjercicioAsignado")
                        .WithMany()
                        .HasForeignKey("EjercicioAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioAsignado");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SerieRealizada", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.EjercicioRealizado", "EjercicioRealizado")
                        .WithMany()
                        .HasForeignKey("EjercicioRealizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioRealizado");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Socios")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("FitRank_API.Domain.Entities.Socio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Invitaciones");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Navigation("LogrosOtorgados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("Gimnasio")
                        .IsRequired();

                    b.Navigation("asistencias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("asistencias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.Navigation("FotosProgreso");

                    b.Navigation("MedidasCorporales");

                    b.Navigation("asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
