// <auto-generated />
using System;
using FitRank_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitRank_API.Migrations
{
    [DbContext(typeof(FitRankDbContext))]
    partial class FitRankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GymId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionDificultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dificultad")
                        .HasColumnType("integer");

                    b.Property<double>("Multiplicador")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesDificultad");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PuntosMaximos")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntosMinimos")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesDivisiones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.ConfiguracionGrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoMuscular")
                        .HasColumnType("integer");

                    b.Property<double>("MultiplicadorPeso")
                        .HasColumnType("double precision");

                    b.Property<double>("MultiplicadorRepeticiones")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesGrupoMuscular");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("DiaAsignado")
                        .HasColumnType("integer");

                    b.Property<int>("Dificultad")
                        .HasColumnType("integer");

                    b.Property<bool>("EsOpcional")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsSerieCompuesta")
                        .HasColumnType("boolean");

                    b.Property<int>("GrupoMuscular")
                        .HasColumnType("integer");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEntrenamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsistenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("Dificultad")
                        .HasColumnType("integer");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObservacionDelUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntosObtenidos")
                        .HasColumnType("double precision");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsistenciaId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EjerciciosRealizados");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Invitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatosPrellenados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GymId")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MpPaymentId")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gimnasios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.GimnasioLogro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("GimnasioId")
                        .HasColumnType("integer");

                    b.Property<int>("LogroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.HasIndex("GimnasioId", "LogroId")
                        .IsUnique();

                    b.ToTable("GimnasioLogro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.PuntuacionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Puntos")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntosAsistencia")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntosEjercicios")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PuntuacionesDiarias");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<double>("PuntosTotales")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasPorSemana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("CuotaPagadaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsActivado")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("text");

                    b.Property<int?>("alturaCm")
                        .HasColumnType("integer");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("dni")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nivel")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("pesoKg")
                        .HasColumnType("double precision");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("asistencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ejercicio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Maquina", "Maquina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Rutina", "Rutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId");

                    b.Navigation("Maquina");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.EjercicioRealizado", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Asistencia", "Asistencia")
                        .WithMany()
                        .HasForeignKey("AsistenciaId");

                    b.HasOne("FitRank_API.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ejerciciosRealizados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Ejercicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.PuntuacionDiaria", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("puntuacionesDiarias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Ranking", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("rutinas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Maquina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("asistencias");

                    b.Navigation("ejerciciosRealizados");

                    b.Navigation("puntuacionesDiarias");

                    b.Navigation("rutinas");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GimnasioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SocioRealizaLogro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaOtorgado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GimnasioId")
                        .HasColumnType("integer");

                    b.Property<int>("LogroId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GimnasioId");

                    b.HasIndex("LogroId");

                    b.HasIndex("SocioId", "LogroId")
                        .IsUnique();

                    b.ToTable("SocioRealizaLogro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.GimnasioLogro", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Logros")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany("Socios")
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.SocioRealizaLogro", b =>
                {
                    b.HasOne("FitRank_API.Domain.Entities.Gimnasio", "Gimnasio")
                        .WithMany()
                        .HasForeignKey("GimnasioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Logro", "Logro")
                        .WithMany("Otorgamientos")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Domain.Entities.Socio", "Socio")
                        .WithMany("LogrosOtorgados")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gimnasio");

                    b.Navigation("Logro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Gimnasio", b =>
                {
                    b.Navigation("Logros");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Logro", b =>
                {
                    b.Navigation("Otorgamientos");
                });

            modelBuilder.Entity("FitRank_API.Domain.Entities.Socio", b =>
                {
                    b.Navigation("LogrosOtorgados");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.BloqueDiaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBloqueRutina")
                        .HasColumnType("integer");

                    b.Property<int>("IdDia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBloqueRutina");

                    b.HasIndex("IdDia");

                    b.ToTable("BloquesDias");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.BloqueRutinaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdRutina")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdRutina");

                    b.ToTable("BloquesRutinas");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.DiaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dias");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.EjercicioBloqueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBloqueRutina")
                        .HasColumnType("integer");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Rir")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBloqueRutina");

                    b.HasIndex("IdEjercicio");

                    b.ToTable("EjerciciosBloques");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.EjercicioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.RutinaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FrecuenciaSemanal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.BloqueDiaEntity", b =>
                {
                    b.HasOne("FitRank_API.Infrastructure.Persistence.BloqueRutinaEntity", "BloqueRutina")
                        .WithMany("Dias")
                        .HasForeignKey("IdBloqueRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Infrastructure.Persistence.DiaEntity", "Dia")
                        .WithMany("BloquesDias")
                        .HasForeignKey("IdDia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueRutina");

                    b.Navigation("Dia");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.BloqueRutinaEntity", b =>
                {
                    b.HasOne("FitRank_API.Infrastructure.Persistence.RutinaEntity", "Rutina")
                        .WithMany("Bloques")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.EjercicioBloqueEntity", b =>
                {
                    b.HasOne("FitRank_API.Infrastructure.Persistence.BloqueRutinaEntity", "BloqueRutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("IdBloqueRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitRank_API.Infrastructure.Persistence.EjercicioEntity", "Ejercicio")
                        .WithMany("EjerciciosBloques")
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueRutina");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.BloqueRutinaEntity", b =>
                {
                    b.Navigation("Dias");

                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.DiaEntity", b =>
                {
                    b.Navigation("BloquesDias");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.EjercicioEntity", b =>
                {
                    b.Navigation("EjerciciosBloques");
                });

            modelBuilder.Entity("FitRank_API.Infrastructure.Persistence.RutinaEntity", b =>
                {
                    b.Navigation("Bloques");
                });
#pragma warning restore 612, 618
        }
    }
}
