name: CI - Build & Test Backend


on:
  push:
    branches:
      - main
      - 'dev-*'
  pull_request:
    branches:
      - main
      - 'dev-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout código
        uses: actions/checkout@v3

      
      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependencias
        run: dotnet restore ./FitRank-API.sln

      
      - name: Build
        run: dotnet build ./FitRank-API.sln --no-restore --configuration Release

      
      - name: Test
        run: dotnet test ./FitRank-API.sln --no-build --verbosity normal
